services:
  db:
    image: postgres:17
    container_name: db_videos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./bot/.env

  bot:
    image: bot:latest
    container_name: tg_bot
    depends_on:
      - db
    volumes:
      - .:/bot
    env_file:
      - ./bot/.env
    command: bash -c "
      poetry run python -m bot.db.init_db && \
      poetry run python -m bot.db.load-json && \
      poetry run python -m bot.main"


volumes:
  postgres_data:
